# Generated by Django 3.1.1 on 2020-10-24 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_status', models.BooleanField(default=False)),
                ('bid_created', models.DateTimeField(auto_now_add=True)),
                ('bid_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_title', models.CharField(max_length=250)),
                ('placement_slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='PlacementBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.IntegerField()),
                ('shares', models.IntegerField()),
                ('confirmed', models.BooleanField(default=False)),
                ('placement_bid_created', models.DateTimeField(auto_now_add=True)),
                ('placement_bid_modified', models.DateTimeField(auto_now=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.bid')),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.placement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['placement_bid_modified'],
            },
        ),
    ]
